// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiWY9MFT6_errdb3ETt1hIw8AALQ_-AXI',
    appId: '1:535415861671:web:a43b2c5a81913924e50682',
    messagingSenderId: '535415861671',
    projectId: 'purple-brick-io',
    authDomain: 'purple-brick-io.firebaseapp.com',
    storageBucket: 'purple-brick-io.appspot.com',
    measurementId: 'G-ER8631LDH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8CqyitGONIM5F6OIupgaMLyB78ZCA-m4',
    appId: '1:535415861671:android:bbd83c0b813a7989e50682',
    messagingSenderId: '535415861671',
    projectId: 'purple-brick-io',
    storageBucket: 'purple-brick-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCITt2R8DzA9DUiHlQTbLkkpL_MhgsQ1io',
    appId: '1:535415861671:ios:41fe4c46b1838fb3e50682',
    messagingSenderId: '535415861671',
    projectId: 'purple-brick-io',
    storageBucket: 'purple-brick-io.appspot.com',
    iosClientId:
        '535415861671-6qhh9u8rjt379oidfc01ajpv0rhrfe3e.apps.googleusercontent.com',
    iosBundleId: 'com.realogy.realogy',
  );
}
